### ISSUE TITLE
如果最后没有一个空行将导致“语法错误 -1 行”

### ISSUE THREAD

**Issue by HamiltonHuaji** [FlyAndNotDown/CSub-CompilerFrontend#1]
将test.c最后的一个换行符删掉会导致语法分析和语义分析失败。换成
`void main(){return;}`则不会报错，但任何汇编代码均不会被给出。

似乎最后没有换行符导致语法分析和语义分析失败的情况只会发生在源文件多于一行的情况。

不知这是bug还是feature？

**Comment by FlyAndNotDown** [comment]
应该是 bug，估计与我词法分析器的设计有关系，但我现在暂时没时间改了 ...
